### ISSUE TITLE
With Neo4j 3.0.x, Cypher query returning 2 results per record (one with actual value, one with null)

### ISSUE THREAD

**Issue by suchcto** [AnormCypher/AnormCypher#55] opened 2016-05-07 11:22 UTC
Hi,

Thanks for implementing this library. I am still very new to neo4j.

When i tried out the code example from the docs (as mentioned below), I got UnExpectedNullableException. I managed to figure out why. Each record in the result set is duplicated (one with actual value, one with null). I tried with 0.8.1 version and it works as expected. Here is the code I used:

Code below return duplicate row at v0.9.0
```
import org.anormcypher._
  import play.api.libs.ws._

  val wsclient = ning.NingWSClient()
  implicit val connection = Neo4jREST()(wsclient)
  implicit val ec = scala.concurrent.ExecutionContext.global

  Cypher("""create (anorm:anormcyphertest {name:"AnormCypher"})""").execute()
  val req = Cypher("match (n:anormcyphertest) return n.name")
  val stream = req()
  stream.foreach(row => {
    println(row[String]("n.name"))
  })
  Cypher("match (n:anormcyphertest) delete n")()
  wsclient.close()
```

Cheers

**Comment by Kai-Chen** [comment] 2016-05-08 02:21
I believe you've observed what you described; there's no obvious reason to think otherwise.  But something quite strange is going on here.  This library is a very small and simple one, being essentially just a specific JSON mapper.  So if the result is not in the original REST response, it's very hard to believe that the library would manufacture one out of nothing.  Furthermore, if the library is consistently misbehaving like this, all our current tests would fail.  But all the tests pass before we push a release out.  Therefore, the cause is much more likely to be somewhere else, for example, in the environment you are running in.

The code that you've pasted in above actually won't work with 0.9.0. You need the following type annotation to bring in a required implicit conversion
```scala
 implicit val connection: Neo4jConnection = Neo4jREST()(wsclient)
```
This is actually my fault, as I didn't update README.  I will do that right after this comment.

I would recommend running a separate neo4j-shell and verify that you don't have a rogue node created with the label `anormcyphertest` that doesn't have a `name` property.

**Comment by suchcto** [comment] 2016-05-16 05:10
Hi @Kai-Chen Sorry for late response. 
I will try it again and more investigate further on this matter.
Thanks.

**Comment by suchcto** [comment] 2016-05-16 06:44
Hi @Kai-Chen So I tried that again and have the same issue. here is the exact code:

```
import org.anormcypher._
  import play.api.libs.ws._

  // Provide an instance of WSClient
  val wsclient = ning.NingWSClient()

  // Setup the Rest Client
  // Need to add the Neo4jConnection type annotation so that the default
  // Neo4jConnection -> Neo4jTransaction conversion is in the implicit scope
  implicit val connection: Neo4jConnection = Neo4jREST(host = "docker", username = "neo4j", password = "admin")(wsclient)

  // Provide an ExecutionContext
  implicit val ec = scala.concurrent.ExecutionContext.global

  // create some test nodes
  Cypher("""create (anorm:anormcyphertest {name:"AnormCypher"}), (test:anormcyphertest {name:"Test"})""").execute()

  // a simple query
  val req = Cypher("match (n:anormcyphertest) return n.name")

  // get a stream of results back
  val stream = req()

  // get the results and put them into a list
  stream.map(row => {row[String]("n.name")}).foreach(println)

  // remove the test nodes
  Cypher("match (n:anormcyphertest) delete n")()

  // shut down WSClient
  wsclient.close()
```
I got the following this UnexpectedNullableFound(n.name) exception.

If I used row[**Option**[String]], it worked and got following output;
```
Some(AnormCypher)
None
Some(Test)
None
```

Cheers

**Comment by Kai-Chen** [comment] 2016-05-16 23:33
> I am running neo4j 3.0.0 if that helps.
Well, that's the cause.  Neo4j 3.0.x has changed the REST response at the transaction endpoint.  We can probably add a fix to handle that.  However, the 3.0.x release also has a binary driver.  So for your use case, it might be easier just to use the Java driver.  I'm not sure if it provides non-blocking streaming, which might be the only reason left to use anormcypher in preference over the binary.

**Comment by Kai-Chen** [comment] 2016-05-19 02:50
This simple query response is easy to fix for anorm to work with Neo4j 3.  But quite a few other tests are failing.  So to completely support Neo4j 3 may take a while; we will do a patch release when it's done.

**Comment by Kai-Chen** [comment] 2016-05-20 16:02
The new release 0.9.1 should support Neo4j 3.0.

Cheers!

**Comment by Kai-Chen** [comment] 2016-06-25 19:48
Closing since there is no further comments in the past month.

**Closed by Kai-Chen** 2016-06-25 19:48 UTC
Labels: enhancement
