### ISSUE TITLE
Exception in maven project

### ISSUE THREAD

**Issue by ahkimkoo** [AnormCypher/AnormCypher#45] opened 2015-07-27 05:06 UTC
```
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at org.anormcypher.Neo4jREST.<init>(Neo4jREST.scala:14)
	at org.anormcypher.Neo4jREST$.apply(Neo4jREST.scala:56)
	at TagML$.<init>(TagML.scala:26)
	at TagML$.<clinit>(TagML.scala)
	at TagML.main(TagML.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:665)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:170)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:193)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

And here is my code

```
import scala.collection.JavaConverters._
import org.ansj.splitWord.analysis.NlpAnalysis
import org.ansj.splitWord.analysis.ToAnalysis
import org.apache.hadoop.hbase.client._
import org.apache.hadoop.hbase.{HBaseConfiguration, HTableDescriptor, TableName}
import org.apache.hadoop.hbase.filter.PageFilter
import org.apache.hadoop.hbase.filter.SingleColumnValueFilter
import org.apache.hadoop.hbase.filter.CompareFilter.CompareOp
import org.apache.hadoop.hbase.mapreduce.TableInputFormat
import org.apache.hadoop.hbase.protobuf.ProtobufUtil
import org.apache.hadoop.hbase.util.{Base64, Bytes}
import com.feheadline.com.backend.recommend.util.Env
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
import org.apache.spark.rdd._
import org.apache.spark.mllib.feature.{Word2Vec, Word2VecModel}
import org.anormcypher._

object TagML {
//.....
//exception here
  implicit val connection = Neo4jREST(
        "tree",
        7474,
       "/db/data/"
      )
//......

}

```

**Comment by ahkimkoo** [comment] 2015-07-27 06:15
help.... waiting here

**Comment by wfreeman** [comment] 2015-07-27 12:49
I have a feeling it's a scala version mismatch or something. You don't really give enough details to reproduce.

**Comment by Kai-Chen** [comment] 2015-10-27 18:53
Closing because this is not related to the AnormCypher library and most likely an issue of environment.  If you still have questions about how to make this work, please address it on the group's mailing list.

**Closed by Kai-Chen** 2015-10-27 18:53 UTC
